import React,{useEffect,useState} from 'react';import {Link,Navigate} from 'react-router-dom';import Seo from '../components/Seo';import {useAuth} from '../context/AuthContext';import {api} from '../lib/api';import {money,date} from '../lib/format';
export default function Account(){const {user,session,loading,signOut}=useAuth();const [orders,setOrders]=useState([]),[addresses,setAddresses]=useState([]);
 useEffect(()=>{if(!session)return;const h={Authorization:`Bearer ${session.access_token}`};Promise.all([api('/account/orders',{headers:h}),api('/account/addresses',{headers:h})]).then(([o,a])=>{setOrders(o.orders);setAddresses(a.addresses)}).catch(()=>{})},[session?.access_token]);
 if(loading)return <div className="loading-page">Opening your account…</div>;if(!user)return <Navigate to="/login/" replace/>;
 return <><Seo title="My account" description="Your Ivy & Pearls account." path="/account/" noindex/><section className="account-hero"><div><p className="eyebrow">Your account</p><h1>Good to see <em>you.</em></h1><p>{user.email}</p></div><button className="text-button" onClick={signOut}>Sign out</button></section><section className="account-grid">
 <article><div className="account-panel__head"><h2>Orders</h2><Link to="/shop/">Shop ↗</Link></div>{orders.length?orders.map(o=><Link className="order-row" to={`/account/orders/${o.order_number}/`} key={o.id}><div><b>{o.order_number}</b><span>{date(o.created_at)}</span></div><div><span>{o.status.replaceAll('_',' ')}</span><strong>{money(o.total_minor,o.currency)}</strong></div></Link>):<p>No orders yet. When you place an order, its progress and tracking will appear here.</p>}</article>
 <article><div className="account-panel__head"><h2>Delivery addresses</h2><Link to="/account/addresses/">Manage ↗</Link></div>{addresses.length?addresses.slice(0,2).map(a=><address key={a.id}>{a.first_name} {a.last_name}<br/>{a.address1}<br/>{a.city}, {a.postcode}</address>):<p>No saved addresses yet.</p>}</article>
 </section></>
}
