import React,{useEffect,useState} from 'react';import {Navigate} from 'react-router-dom';import Seo from '../components/Seo';import {useAuth} from '../context/AuthContext';import {api} from '../lib/api';
const blank={label:'Delivery',first_name:'',last_name:'',phone:'',address1:'',address2:'',city:'',province:'',postcode:'',country_code:'GB',is_default:false};
export default function Addresses(){const {user,session,loading}=useAuth();const [addresses,setAddresses]=useState([]),[form,setForm]=useState(blank),[state,setState]=useState('');
 const headers=session?{Authorization:`Bearer ${session.access_token}`}:{};
 const load=()=>session&&api('/account/addresses',{headers}).then(r=>setAddresses(r.addresses));
 useEffect(()=>{load()},[session?.access_token]);
 if(!loading&&!user)return <Navigate to="/login/" replace/>;
 const f=n=>({value:form[n],onChange:e=>setForm(x=>({...x,[n]:e.target.type==='checkbox'?e.target.checked:e.target.value}))});
 async function submit(e){e.preventDefault();setState('Saving…');try{await api('/account/addresses',{method:'POST',headers,body:JSON.stringify(form)});setForm(blank);setState('Saved.');load()}catch(e){setState(e.message)}}
 async function remove(id){await api(`/account/addresses/${id}`,{method:'DELETE',headers});load()}
 return <><Seo title="Addresses" description="Manage Ivy & Pearls delivery addresses." path="/account/addresses/" noindex/><section className="page-hero"><div className="container"><p className="eyebrow">Account</p><h1>Delivery <em>addresses.</em></h1></div></section><section className="account-grid addresses-page"><article><h2>Saved addresses</h2>{addresses.length?addresses.map(a=><div className="saved-address" key={a.id}><address>{a.first_name} {a.last_name}<br/>{a.address1}<br/>{a.address2&&<>{a.address2}<br/></>}{a.city}, {a.province}<br/>{a.postcode}</address><button className="text-button" onClick={()=>remove(a.id)}>Remove</button></div>):<p>No saved addresses.</p>}</article><article><h2>Add an address</h2><form onSubmit={submit} className="checkout-form"><div className="form-grid"><label>First name<input required {...f('first_name')}/></label><label>Last name<input required {...f('last_name')}/></label><label className="span-2">Address<input required {...f('address1')}/></label><label className="span-2">Address line 2<input {...f('address2')}/></label><label>Town / city<input required {...f('city')}/></label><label>County<input required {...f('province')}/></label><label>Postcode<input required {...f('postcode')}/></label><label>Phone<input required {...f('phone')}/></label></div><label className="check-line"><input type="checkbox" checked={form.is_default} onChange={f('is_default').onChange}/><span>Use as my default delivery address</span></label><button className="button button--dark">Save address</button><p>{state}</p></form></article></section></>
}
