import React,{useEffect,useState} from 'react';
import Seo from '../components/Seo';
import {useAuth} from '../context/AuthContext';
import {api} from '../lib/api';
import {money,date,slugify} from '../lib/format';

export default function Admin(){
 const {session,user,loading}=useAuth();const [tab,setTab]=useState('overview'),[data,setData]=useState(null),[error,setError]=useState('');
 const headers=session?{Authorization:`Bearer ${session.access_token}`}:{};
 useEffect(()=>{if(session)loadOverview()},[session?.access_token]);
 async function loadOverview(){try{setData(await api('/admin/dashboard',{headers}));setError('')}catch(e){setError(e.message)}}
 if(loading)return <div className="loading-page">Loading admin…</div>;
 if(!user)return <section className="section container"><h1>Sign in required</h1><p>Administrator access is required.</p></section>;
 if(error)return <section className="section container"><h1>Admin</h1><p>{error}</p></section>;
 return <><Seo title="Admin" description="Ivy & Pearls administration." path="/admin/" noindex/><section className="admin-shell"><aside className="admin-nav"><div><p className="eyebrow">Ivy &amp; Pearls</p><h1>Admin</h1></div>{['overview','products','zq import','orders'].map(x=><button key={x} className={tab===x?'is-active':''} onClick={()=>setTab(x)}>{x}</button>)}</aside><main className="admin-main">
 {tab==='overview'&&<Overview data={data}/>}
 {tab==='products'&&<Products headers={headers}/>}
 {tab==='zq import'&&<ZqImport headers={headers}/>}
 {tab==='orders'&&<Orders headers={headers}/>}
 </main></section></>
}

function Overview({data}){return <><div className="admin-title"><p className="eyebrow">Overview</p><h2>Store at a glance.</h2></div><div className="admin-stats"><div><span>Products</span><b>{data?.products??0}</b></div><div><span>Orders</span><b>{data?.orders??0}</b></div><div><span>New messages</span><b>{data?.newMessages??0}</b></div></div><section className="admin-panel"><h3>Recent orders</h3>{data?.recentOrders?.map(o=><div className="admin-row" key={o.order_number}><span>{o.order_number}</span><span>{o.status.replaceAll('_',' ')}</span><span>{money(o.total_minor)}</span><span>{date(o.created_at)}</span></div>)}</section></>}

function Products({headers}){const [products,setProducts]=useState([]),[state,setState]=useState('');const load=()=>api('/admin/products',{headers}).then(r=>setProducts(r.products));useEffect(()=>{load()},[]);
 async function patch(id,body){setState('Saving…');try{await api(`/admin/products/${id}`,{method:'PATCH',headers,body:JSON.stringify(body)});setState('Saved.');load()}catch(e){setState(e.message)}}
 async function patchVariant(id,body){setState('Saving…');try{await api(`/admin/variants/${id}`,{method:'PATCH',headers,body:JSON.stringify(body)});setState('Saved.');load()}catch(e){setState(e.message)}}
 return <><div className="admin-title"><p className="eyebrow">Catalogue</p><h2>Products.</h2><p>{state}</p></div>{products.map(p=><details className="admin-product" key={p.id}><summary><span>{p.title}</span><span>{p.status}</span></summary><div className="admin-product__body"><label>Title<input defaultValue={p.title} onBlur={e=>e.target.value!==p.title&&patch(p.id,{title:e.target.value})}/></label><label>Short description<textarea defaultValue={p.short_description||''} onBlur={e=>patch(p.id,{short_description:e.target.value})}/></label><div className="admin-flags"><label><input type="checkbox" checked={p.featured} onChange={e=>patch(p.id,{featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={p.new_arrival} onChange={e=>patch(p.id,{new_arrival:e.target.checked})}/> New arrival</label><label><input type="checkbox" checked={p.ivy_edit} onChange={e=>patch(p.id,{ivy_edit:e.target.checked})}/> Ivy Edit</label></div><label>Status<select value={p.status} onChange={e=>patch(p.id,{status:e.target.value})}><option>draft</option><option>active</option><option>archived</option></select></label><h4>Variants</h4>{p.product_variants?.map(v=><div className="variant-admin" key={v.id}><span>{v.title}<small>{v.zq_sku}</small></span><label>Retail price (£)<input type="number" step=".01" defaultValue={(v.price_minor/100).toFixed(2)} onBlur={e=>patchVariant(v.id,{price_minor:Math.round(Number(e.target.value)*100)})}/></label><label><input type="checkbox" checked={v.active} onChange={e=>patchVariant(v.id,{active:e.target.checked})}/> Active</label></div>)}</div></details>)}</>}

function ZqImport({headers}){const [q,setQ]=useState(''),[records,setRecords]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({title:'',slug:'',category:'earrings',collection:'',retailPricePounds:99,shortDescription:'',description:'',materialSummary:'',active:false}),[state,setState]=useState('');
 async function search(e){e?.preventDefault();setState('Searching ZQ…');try{const r=await api(`/admin/zq/products?q=${encodeURIComponent(q)}`,{headers});setRecords(r.records||[]);setState('')}catch(e){setState(e.message)}}
 async function choose(id){setState('Loading product…');try{const r=await api(`/admin/zq/products/${id}`,{headers});setSelected(r.product);setForm(f=>({...f,title:r.product.subject||'',slug:slugify(r.product.subject||''),description:r.product.description||''}));setState('')}catch(e){setState(e.message)}}
 async function submit(e){e.preventDefault();setState('Importing…');try{const r=await api(`/admin/zq/import/${selected.id}`,{method:'POST',headers,body:JSON.stringify({...form,retailPricePounds:Number(form.retailPricePounds)})});setState(`Imported ${r.slug}. Review it in Products before publishing.`);setSelected(null)}catch(e){setState(e.message)}}
 const f=n=>({value:form[n],onChange:e=>setForm(x=>({...x,[n]:e.target.type==='checkbox'?e.target.checked:e.target.value}))});
 return <><div className="admin-title"><p className="eyebrow">ZQ catalogue</p><h2>Import a product.</h2><p>Search your ZQ import list, inspect the source item, set your Ivy & Pearls retail presentation and import it into Supabase.</p></div><form className="admin-search" onSubmit={search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Product name, ID or SKU"/><button className="button button--dark">Search ZQ</button></form><p>{state}</p><div className="zq-grid">{records.map(r=><button className="zq-card" onClick={()=>choose(r.id)} key={r.id}>{r.images?.[0]?.image&&<img src={r.images[0].image} alt=""/>}<span>{r.subject}</span><small>#{r.id}</small></button>)}</div>{selected&&<div className="admin-modal"><form onSubmit={submit}><button type="button" className="admin-modal__close" onClick={()=>setSelected(null)}>×</button><h3>Prepare for Ivy &amp; Pearls</h3><div className="form-grid"><label>Product title<input required {...f('title')}/></label><label>URL slug<input required pattern="[a-z0-9-]+" {...f('slug')}/></label><label>Category<select {...f('category')}><option value="rings">Rings</option><option value="necklaces">Necklaces</option><option value="earrings">Earrings</option><option value="bracelets">Bracelets</option></select></label><label>Retail price (£)<input type="number" min="1" step=".01" {...f('retailPricePounds')}/></label><label className="span-2">Short description<textarea {...f('shortDescription')}/></label><label className="span-2">Material summary<textarea {...f('materialSummary')} placeholder="Only enter verified material information."/></label></div><label className="check-line"><input type="checkbox" checked={form.active} onChange={f('active').onChange}/><span>Publish immediately (otherwise imports as draft)</span></label><button className="button button--dark">Import product</button></form></div>}</>}

function Orders({headers}){const [orders,setOrders]=useState([]),[state,setState]=useState('');const load=()=>api('/admin/orders',{headers}).then(r=>setOrders(r.orders));useEffect(()=>{load()},[]);
 async function retry(id){setState('Submitting to ZQ…');try{await api(`/admin/orders/${id}/retry-zq`,{method:'POST',headers});setState('Submitted.');load()}catch(e){setState(e.message)}}
 return <><div className="admin-title"><p className="eyebrow">Orders</p><h2>Fulfilment.</h2><p>{state}</p></div><div className="admin-orders">{orders.map(o=><details key={o.id}><summary><b>{o.order_number}</b><span>{o.status.replaceAll('_',' ')}</span><span>{money(o.total_minor)}</span><span>{date(o.created_at)}</span></summary><div className="admin-order-body"><p>{o.email}</p><p>ZQ: {o.zq_platform_order_id||'Not yet submitted'} · {o.zq_status||'—'}</p><p>Tracking: {o.tracking_number||'Awaiting tracking'}</p>{o.order_items?.map(i=><p key={i.id}>{i.product_name} · {i.variant_name} × {i.quantity}</p>)}{o.status==='fulfilment_error'&&<button className="button button--dark" onClick={()=>retry(o.id)}>Retry ZQ fulfilment</button>}</div></details>)}</div></>}
