import React,{useEffect,useMemo,useState} from 'react';
import Seo from '../components/Seo';
import {useAuth} from '../context/AuthContext';
import {api} from '../lib/api';
import {money,date,slugify} from '../lib/format';

const NAV=['overview','products','catalogue','zq import','orders'];
const PRODUCT_TABS=['general','pricing','inventory','variants','attributes','media','organisation','seo','shipping','zq','advanced'];

export default function Admin(){
 const {session,user,loading}=useAuth();const [tab,setTab]=useState('overview'),[data,setData]=useState(null),[error,setError]=useState('');
 const headers=session?{Authorization:`Bearer ${session.access_token}`}:{ };
 useEffect(()=>{if(session)loadOverview()},[session?.access_token]);
 async function loadOverview(){try{setData(await api('/admin/dashboard',{headers}));setError('')}catch(e){setError(e.message)}}
 if(loading)return <div className="loading-page">Loading admin…</div>;
 if(!user)return <section className="section container"><h1>Sign in required</h1><p>Administrator access is required.</p></section>;
 if(error)return <section className="section container"><h1>Admin</h1><p>{error}</p></section>;
 return <><Seo title="Admin" description="Ivy & Pearls administration." path="/admin/" noindex/><section className="admin-shell"><aside className="admin-nav"><div><p className="eyebrow">Ivy &amp; Pearls</p><h1>Admin</h1></div>{NAV.map(x=><button key={x} className={tab===x?'is-active':''} onClick={()=>setTab(x)}>{x}</button>)}</aside><main className="admin-main">
 {tab==='overview'&&<Overview data={data}/>} {tab==='products'&&<Products headers={headers}/>} {tab==='catalogue'&&<Catalogue headers={headers}/>} {tab==='zq import'&&<ZqImport headers={headers}/>} {tab==='orders'&&<Orders headers={headers}/>} </main></section></>
}

function Overview({data}){return <><div className="admin-title"><p className="eyebrow">Overview</p><h2>Store at a glance.</h2></div><div className="admin-stats"><div><span>Products</span><b>{data?.products??0}</b></div><div><span>Orders</span><b>{data?.orders??0}</b></div><div><span>New messages</span><b>{data?.newMessages??0}</b></div></div><section className="admin-panel"><h3>Recent orders</h3>{data?.recentOrders?.map(o=><div className="admin-row" key={o.order_number}><span>{o.order_number}</span><span>{o.status.replaceAll('_',' ')}</span><span>{money(o.total_minor)}</span><span>{date(o.created_at)}</span></div>)}</section></>}

function Products({headers}){
 const [products,setProducts]=useState([]),[selected,setSelected]=useState(null),[state,setState]=useState(''),[q,setQ]=useState('');
 const load=()=>api('/admin/products',{headers}).then(r=>setProducts(r.products||[]));useEffect(()=>{load()},[]);
 const visible=products.filter(p=>(p.title+' '+p.slug+' '+p.status).toLowerCase().includes(q.toLowerCase()));
 return <><div className="admin-title admin-title--toolbar"><div><p className="eyebrow">Catalogue</p><h2>Products.</h2><p>Import from ZQ as a supplier-linked draft, then control exactly what customers see here.</p></div><input className="admin-filter" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products…"/></div>{state&&<p className="admin-notice">{state}</p>}<div className="admin-product-table"><div className="admin-product-table__head"><span>Product</span><span>Status</span><span>Price</span><span>Stock</span><span>Supplier</span></div>{visible.map(p=>{const variants=p.product_variants||[],prices=variants.map(v=>v.price_minor),stock=variants.reduce((a,v)=>a+(v.inventory_quantity||0),0);return <button key={p.id} className="admin-product-line" onClick={()=>setSelected(p.id)}><span className="admin-product-line__title">{p.product_images?.[0]&&<img src={p.product_images.sort((a,b)=>a.sort_order-b.sort_order)[0].url} alt=""/>}<span><b>{p.title}</b><small>/{p.slug}/</small></span></span><span><StatusPill status={p.status}/></span><span>{prices.length?money(Math.min(...prices)):'—'}</span><span>{stock}</span><span>{p.zq_product_id||variants.find(v=>v.zq_product_id)?.zq_product_id?'ZQ linked':'Manual'}</span></button>})}</div>{selected&&<ProductEditor id={selected} headers={headers} onClose={()=>{setSelected(null);load()}} setState={setState}/>}</>;
}

function StatusPill({status}){return <span className={`admin-status admin-status--${status}`}>{String(status).replaceAll('_',' ')}</span>}

function ProductEditor({id,headers,onClose,setState}){
 const [product,setProduct]=useState(null),[meta,setMeta]=useState(null),[tab,setTab]=useState('general'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const [p,m]=await Promise.all([api(`/admin/products/${id}/detail`,{headers}),api('/admin/catalogue-meta',{headers})]);setProduct(p.product);setMeta(m)};useEffect(()=>{load()},[id]);
 const patch=async(body)=>{setBusy(true);try{const r=await api(`/admin/products/${id}`,{method:'PATCH',headers,body:JSON.stringify(body)});setProduct(x=>({...x,...r.product}));setMessage('Saved.')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 if(!product||!meta)return <div className="admin-modal"><div className="admin-editor admin-editor--loading">Loading product…</div></div>;
 const categoryIds=(product.product_categories||[]).map(x=>x.category_id),collectionIds=(product.product_collections||[]).map(x=>x.collection_id),tagIds=(product.product_tags||[]).map(x=>x.tag_id);
 const saveMerch=async(next={})=>{setBusy(true);try{await api(`/admin/products/${id}/merchandising`,{method:'PUT',headers,body:JSON.stringify({categoryIds:next.categoryIds??categoryIds,collectionIds:next.collectionIds??collectionIds,tagIds:next.tagIds??tagIds,attributes:next.attributes??(product.product_attributes||[]).map((a,i)=>({attribute_id:a.attribute_id,name:a.name,values:Array.isArray(a.values)?a.values:[],visible:a.visible,used_for_variations:a.used_for_variations,sort_order:i}))})});await load();setMessage('Merchandising saved.')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 return <div className="admin-modal admin-modal--editor"><div className="admin-editor"><header className="admin-editor__head"><div><p className="eyebrow">Edit product</p><h2>{product.title}</h2><div className="admin-editor__meta"><StatusPill status={product.status}/><span>{product.zq_product_id?`ZQ #${product.zq_product_id}`:'Manual product'}</span>{busy&&<span>Saving…</span>}{message&&<span>{message}</span>}</div></div><button className="admin-editor__close" onClick={onClose} aria-label="Close editor">×</button></header><div className="admin-editor__layout"><nav className="admin-editor__tabs">{PRODUCT_TABS.map(t=><button key={t} className={tab===t?'is-active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><section className="admin-editor__content">
 {tab==='general'&&<GeneralTab product={product} patch={patch}/>} {tab==='pricing'&&<PricingTab product={product} headers={headers} load={load}/>} {tab==='inventory'&&<InventoryTab product={product} headers={headers} load={load}/>} {tab==='variants'&&<VariantsTab product={product} headers={headers} load={load}/>} {tab==='attributes'&&<AttributesTab product={product} meta={meta} save={saveMerch}/>} {tab==='media'&&<MediaTab product={product} headers={headers} load={load}/>} {tab==='organisation'&&<OrganisationTab product={product} meta={meta} patch={patch} save={saveMerch}/>} {tab==='seo'&&<SeoTab product={product} patch={patch}/>} {tab==='shipping'&&<ShippingTab product={product} patch={patch}/>} {tab==='zq'&&<ZqTab product={product} headers={headers} load={load}/>} {tab==='advanced'&&<AdvancedTab product={product} patch={patch}/>} </section></div><footer className="admin-editor__foot"><button className="button" onClick={onClose}>Close</button><a className="button button--dark" href={`/product/${product.slug}/`} target="_blank" rel="noreferrer">Preview ↗</a></footer></div></div>;
}

function Field({label,children,hint,className=''}){return <label className={`admin-field ${className}`}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function SaveInput({label,value='',onSave,type='text',hint}){const [v,setV]=useState(value??'');useEffect(()=>setV(value??''),[value]);return <Field label={label} hint={hint}><input type={type} value={v} onChange={e=>setV(e.target.value)} onBlur={()=>String(v)!==String(value??'')&&onSave(type==='number'?Number(v):v)}/></Field>}
function SaveText({label,value='',onSave,rows=5,hint}){const [v,setV]=useState(value??'');useEffect(()=>setV(value??''),[value]);return <Field label={label} hint={hint}><textarea rows={rows} value={v} onChange={e=>setV(e.target.value)} onBlur={()=>v!==(value??'')&&onSave(v)}/></Field>}

function GeneralTab({product,patch}){return <div className="admin-tab"><h3>General</h3><div className="admin-form-grid"><SaveInput label="Product title" value={product.title} onSave={title=>patch({title})}/><SaveInput label="URL slug" value={product.slug} onSave={slug=>patch({slug:slugify(slug)})}/><SaveInput label="Subtitle" value={product.subtitle} onSave={subtitle=>patch({subtitle})}/><SaveInput label="Internal SKU" value={product.internal_sku} onSave={internal_sku=>patch({internal_sku})}/><Field label="Status"><select value={product.status} onChange={e=>patch({status:e.target.value})}><option value="draft">Draft</option><option value="needs_review">Needs review</option><option value="ready">Ready</option><option value="active">Published</option><option value="archived">Archived</option><option value="supplier_unavailable">Supplier unavailable</option></select></Field><Field label="Visibility"><select value={product.visibility||'catalog_search'} onChange={e=>patch({visibility:e.target.value})}><option value="catalog_search">Shop & search</option><option value="catalog">Shop only</option><option value="search">Search only</option><option value="hidden">Hidden</option></select></Field></div><SaveText label="Short description" value={product.short_description} rows={4} onSave={short_description=>patch({short_description})}/><SaveText label="Full description (safe HTML supported)" value={product.description} rows={12} onSave={description=>patch({description})}/><SaveText label="Materials / product clarity" value={product.material_summary} rows={5} onSave={material_summary=>patch({material_summary})} hint="Only publish material claims you have verified."/><SaveText label="Care" value={product.care} rows={5} onSave={care=>patch({care})}/></div>}

function PricingTab({product,headers,load}){const variants=product.product_variants||[];async function save(v,body){await api(`/admin/variants/${v.id}`,{method:'PATCH',headers,body:JSON.stringify(body)});load()}return <div className="admin-tab"><h3>Pricing</h3><p className="admin-help">Retail pricing is controlled by Ivy &amp; Pearls and is never overwritten by ZQ sync.</p>{variants.map(v=><div className="admin-variant-card" key={v.id}><div><b>{v.title}</b><small>{v.sku}</small></div><MoneyEditor label="Retail price" value={v.price_minor} onSave={price_minor=>save(v,{price_minor})}/><MoneyEditor label="Compare-at price" value={v.compare_at_minor} nullable onSave={compare_at_minor=>save(v,{compare_at_minor})}/><div><span>Supplier cost</span><b>{v.cost_minor!=null?money(v.cost_minor):'—'}</b></div><div><span>Gross margin</span><b>{v.cost_minor!=null&&v.price_minor?`${Math.round((1-v.cost_minor/v.price_minor)*100)}%`:'—'}</b></div></div>)}</div>}
function MoneyEditor({label,value,onSave,nullable}){const [v,setV]=useState(value==null?'':(value/100).toFixed(2));useEffect(()=>setV(value==null?'':(value/100).toFixed(2)),[value]);return <Field label={`${label} (£)`}><input type="number" min="0" step="0.01" value={v} onChange={e=>setV(e.target.value)} onBlur={()=>onSave(v===''&&nullable?null:Math.round(Number(v||0)*100))}/></Field>}

function InventoryTab({product,headers,load}){async function save(v,body){await api(`/admin/variants/${v.id}`,{method:'PATCH',headers,body:JSON.stringify(body)});load()}return <div className="admin-tab"><h3>Inventory</h3><p className="admin-help">ZQ-linked stock is supplier data. Your storefront reads the synchronized quantity, while backorder and low-stock behaviour remain under your control.</p>{(product.product_variants||[]).map(v=><div className="admin-variant-card admin-variant-card--inventory" key={v.id}><div><b>{v.title}</b><small>ZQ SKU: {v.zq_sku||'—'}</small></div><Metric label="Available" value={v.inventory_quantity}/><Metric label="Locked" value={v.inventory_locked}/><Metric label="In transit" value={v.inventory_in_transit}/><Field label="Low stock"><input type="number" defaultValue={v.low_stock_threshold??''} onBlur={e=>save(v,{low_stock_threshold:e.target.value===''?null:Number(e.target.value)})}/></Field><label className="admin-check"><input type="checkbox" checked={v.allow_backorder||false} onChange={e=>save(v,{allow_backorder:e.target.checked})}/> Allow backorders</label></div>)}</div>}
function Metric({label,value}){return <div className="admin-metric"><span>{label}</span><b>{value??0}</b></div>}

function VariantsTab({product,headers,load}){const [adding,setAdding]=useState(false);async function save(v,body){await api(`/admin/variants/${v.id}`,{method:'PATCH',headers,body:JSON.stringify(body)});load()}async function remove(id){if(!confirm('Delete this variant?'))return;await api(`/admin/variants/${id}`,{method:'DELETE',headers});load()}return <div className="admin-tab"><div className="admin-tab__head"><div><h3>Variants</h3><p className="admin-help">Customer-facing names and prices are editable; hidden ZQ SKU/spec mappings remain attached for fulfilment.</p></div><button className="button button--dark" onClick={()=>setAdding(!adding)}>+ Variant</button></div>{adding&&<VariantCreator product={product} headers={headers} onDone={()=>{setAdding(false);load()}}/>}{(product.product_variants||[]).sort((a,b)=>a.sort_order-b.sort_order).map(v=><details className="admin-variant-detail" key={v.id}><summary><span><b>{v.title}</b><small>{v.sku}</small></span><span>{money(v.price_minor)}</span><span>{v.inventory_quantity} stock</span><span>{v.active?'Active':'Disabled'}</span></summary><div className="admin-form-grid"><SaveInput label="Variant title" value={v.title} onSave={title=>save(v,{title})}/><SaveInput label="Store SKU" value={v.sku} onSave={sku=>save(v,{sku})}/><SaveInput label="Barcode" value={v.barcode} onSave={barcode=>save(v,{barcode})}/><SaveInput label="Variant image URL" value={v.image_url} onSave={image_url=>save(v,{image_url})}/><Field label="Customer attributes JSON" hint='Example: {"Metal":"18K Yellow Gold","Ring Size":"N"}'><textarea rows="5" defaultValue={JSON.stringify(v.attributes||{},null,2)} onBlur={e=>{try{save(v,{attributes:JSON.parse(e.target.value)})}catch{alert('Invalid JSON')}}}/></Field><Field label="Supplier mapping"><div className="admin-readonly"><span>ZQ SKU</span><b>{v.zq_sku||'—'}</b><span>ZQ spec</span><b>{v.zq_spec_id||'—'}</b></div></Field><label className="admin-check"><input type="checkbox" checked={v.active} onChange={e=>save(v,{active:e.target.checked})}/> Enabled</label><button className="text-button admin-danger" onClick={()=>remove(v.id)}>Delete variant</button></div></details>)}</div>}
function VariantCreator({product,headers,onDone}){const [f,setF]=useState({title:'',sku:'',price:'0.00'});async function submit(e){e.preventDefault();await api(`/admin/products/${product.id}/variants`,{method:'POST',headers,body:JSON.stringify({title:f.title,sku:f.sku,price_minor:Math.round(Number(f.price)*100),attributes:{},active:true})});onDone()}return <form className="admin-inline-create" onSubmit={submit}><input required placeholder="Variant title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input required placeholder="SKU" value={f.sku} onChange={e=>setF({...f,sku:e.target.value})}/><input required type="number" min="0" step=".01" placeholder="Retail £" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/><button className="button button--dark">Create</button></form>}

function AttributesTab({product,meta,save}){const initial=(product.product_attributes||[]).map(a=>({...a,values:Array.isArray(a.values)?a.values:[]}));const [rows,setRows]=useState(initial);useEffect(()=>setRows(initial),[product.id,product.product_attributes?.length]);function addGlobal(id){const a=meta.attributes.find(x=>x.id===id);if(!a)return;setRows(x=>[...x,{attribute_id:a.id,name:a.name,values:[],visible:true,used_for_variations:false,sort_order:x.length}])}return <div className="admin-tab"><h3>Attributes</h3><p className="admin-help">Use reusable attributes such as Ring Size, Metal, Stone, Colour and Finish. Supplier labels can remain hidden while customers see your polished terminology.</p><div className="admin-attribute-add"><select defaultValue="" onChange={e=>{addGlobal(e.target.value);e.target.value=''}}><option value="" disabled>Add global attribute…</option>{meta.attributes.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button className="button" onClick={()=>setRows(x=>[...x,{attribute_id:null,name:'',values:[],visible:true,used_for_variations:false,sort_order:x.length}])}>+ Custom</button></div>{rows.map((a,i)=><div className="admin-attribute-row" key={i}><input value={a.name} onChange={e=>setRows(x=>x.map((r,n)=>n===i?{...r,name:e.target.value}:r))} placeholder="Attribute name"/><input value={a.values.join(', ')} onChange={e=>setRows(x=>x.map((r,n)=>n===i?{...r,values:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)}:r))} placeholder="Values separated by commas"/><label><input type="checkbox" checked={a.visible} onChange={e=>setRows(x=>x.map((r,n)=>n===i?{...r,visible:e.target.checked}:r))}/> Visible</label><label><input type="checkbox" checked={a.used_for_variations} onChange={e=>setRows(x=>x.map((r,n)=>n===i?{...r,used_for_variations:e.target.checked}:r))}/> Variations</label><button onClick={()=>setRows(x=>x.filter((_,n)=>n!==i))}>×</button></div>)}<button className="button button--dark" onClick={()=>save({attributes:rows.map((a,i)=>({...a,sort_order:i}))})}>Save attributes</button></div>}

function MediaTab({product,headers,load}){const [url,setUrl]=useState(''),[alt,setAlt]=useState('');async function add(e){e.preventDefault();await api(`/admin/products/${product.id}/images`,{method:'POST',headers,body:JSON.stringify({url,alt_text:alt,is_primary:!(product.product_images||[]).length})});setUrl('');setAlt('');load()}async function patch(id,body){await api(`/admin/images/${id}`,{method:'PATCH',headers,body:JSON.stringify(body)});load()}async function remove(id){await api(`/admin/images/${id}`,{method:'DELETE',headers});load()}return <div className="admin-tab"><h3>Media</h3><p className="admin-help">ZQ images are source assets. Reorder, rewrite alt text, add your own editorial photography and choose the primary image without changing fulfilment mappings.</p><div className="admin-media-grid">{(product.product_images||[]).sort((a,b)=>a.sort_order-b.sort_order).map(im=><article key={im.id}><img src={im.url} alt={im.alt_text}/><textarea rows="2" defaultValue={im.alt_text} onBlur={e=>patch(im.id,{alt_text:e.target.value})}/><div><button onClick={()=>patch(im.id,{is_primary:true})}>{im.is_primary?'Primary ✓':'Make primary'}</button><button className="admin-danger" onClick={()=>remove(im.id)}>Remove</button></div></article>)}</div><form className="admin-inline-create" onSubmit={add}><input type="url" required placeholder="Image URL" value={url} onChange={e=>setUrl(e.target.value)}/><input placeholder="Alt text" value={alt} onChange={e=>setAlt(e.target.value)}/><button className="button button--dark">Add image</button></form></div>}

function OrganisationTab({product,meta,patch,save}){const categoryIds=(product.product_categories||[]).map(x=>x.category_id),collectionIds=(product.product_collections||[]).map(x=>x.collection_id),tagIds=(product.product_tags||[]).map(x=>x.tag_id);const [cats,setCats]=useState(categoryIds),[cols,setCols]=useState(collectionIds),[tags,setTags]=useState(tagIds);const toggle=(arr,set,id)=>set(arr.includes(id)?arr.filter(x=>x!==id):[...arr,id]);return <div className="admin-tab"><h3>Organisation</h3><div className="admin-form-grid"><Field label="Legacy primary category"><select value={product.category} onChange={e=>patch({category:e.target.value})}><option value="rings">Rings</option><option value="necklaces">Necklaces</option><option value="earrings">Earrings</option><option value="bracelets">Bracelets</option></select></Field><SaveInput label="Legacy collection slug" value={product.collection} onSave={collection=>patch({collection:collection||null})}/></div><TaxonomyBox title="Categories" rows={meta.categories} selected={cats} toggle={id=>toggle(cats,setCats,id)}/><TaxonomyBox title="Collections" rows={meta.collections} selected={cols} toggle={id=>toggle(cols,setCols,id)}/><TaxonomyBox title="Tags" rows={meta.tags} selected={tags} toggle={id=>toggle(tags,setTags,id)}/><div className="admin-flags"><label><input type="checkbox" checked={product.featured} onChange={e=>patch({featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={product.new_arrival} onChange={e=>patch({new_arrival:e.target.checked})}/> New arrival</label><label><input type="checkbox" checked={product.ivy_edit} onChange={e=>patch({ivy_edit:e.target.checked})}/> The Ivy Edit</label></div><button className="button button--dark" onClick={()=>save({categoryIds:cats,collectionIds:cols,tagIds:tags})}>Save organisation</button></div>}
function TaxonomyBox({title,rows,selected,toggle}){return <div className="admin-taxonomy-box"><h4>{title}</h4><div>{rows.map(r=><label key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>toggle(r.id)}/>{r.name}</label>)}</div></div>}

function SeoTab({product,patch}){const [title,setTitle]=useState(product.seo_title||''),[desc,setDesc]=useState(product.seo_description||'');return <div className="admin-tab"><h3>SEO & social</h3><p className="admin-help">This controls the server-rendered title, description, canonical and social preview used by the React storefront.</p><SaveInput label="SEO title" value={product.seo_title} onSave={seo_title=>patch({seo_title})} hint="Aim for a concise, descriptive title rather than keyword stuffing."/><SaveText label="Meta description" value={product.seo_description} rows={3} onSave={seo_description=>patch({seo_description})}/><SaveInput label="Canonical URL" value={product.canonical_url} onSave={canonical_url=>patch({canonical_url:canonical_url||null})}/><SaveInput label="Open Graph title" value={product.og_title} onSave={og_title=>patch({og_title:og_title||null})}/><SaveText label="Open Graph description" value={product.og_description} rows={3} onSave={og_description=>patch({og_description:og_description||null})}/><SaveInput label="Open Graph image URL" value={product.og_image_url} onSave={og_image_url=>patch({og_image_url:og_image_url||null})}/><Field label="Robots"><select value={product.meta_robots||'index,follow'} onChange={e=>patch({meta_robots:e.target.value})}><option value="index,follow">Index, follow</option><option value="noindex,follow">Noindex, follow</option><option value="noindex,nofollow">Noindex, nofollow</option></select></Field><div className="seo-preview"><span>ivyandpearls.co.uk › product › {product.slug}</span><h4>{title||product.title}</h4><p>{desc||product.short_description||'Add a concise search description for this product.'}</p></div></div>}

function ShippingTab({product,patch}){const dims=product.dimensions||{};return <div className="admin-tab"><h3>Shipping</h3><div className="admin-form-grid"><SaveInput label="Country of origin" value={product.country_of_origin} onSave={country_of_origin=>patch({country_of_origin})}/><SaveInput label="Customer-facing lead time" value={product.lead_time} onSave={lead_time=>patch({lead_time})}/><SaveInput label="Tax class" value={product.tax_class||'standard'} onSave={tax_class=>patch({tax_class})}/><Field label="Dimensions (cm)"><div className="admin-dimensions">{['length','width','height'].map(k=><input key={k} type="number" step=".1" placeholder={k} defaultValue={dims[k]||''} onBlur={e=>patch({dimensions:{...dims,[k]:Number(e.target.value||0)}})}/>)}</div></Field></div><SaveText label="Origin / shipping note" value={product.origin_note} onSave={origin_note=>patch({origin_note})}/></div>}

function ZqTab({product,headers,load}){const [fields,setFields]=useState(['inventory','cost','weight','supplier_status']),[state,setState]=useState('');const toggle=f=>setFields(x=>x.includes(f)?x.filter(y=>y!==f):[...x,f]);async function sync(){setState('Syncing…');try{await api(`/admin/products/${product.id}/sync-zq`,{method:'POST',headers,body:JSON.stringify({fields})});setState('ZQ sync complete. Your merchandising fields were not overwritten.');load()}catch(e){setState(e.message)}}return <div className="admin-tab"><h3>ZQ supplier link</h3>{!product.zq_product_id?<p>This product has no ZQ supplier link.</p>:<><div className="admin-zq-card"><div><span>ZQ product</span><b>#{product.zq_product_id}</b></div><div><span>Supplier status</span><b>{product.zq_source_status||'—'}</b></div><div><span>Last synced</span><b>{product.zq_last_synced_at?date(product.zq_last_synced_at):'Never'}</b></div></div><h4>Automatic sync protection</h4><div className="admin-sync-switches">{[['sync_inventory','Inventory'],['sync_cost','Supplier cost'],['sync_weight','Weight'],['sync_supplier_status','Supplier status'],['sync_images','New supplier images']].map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(product[key])} onChange={e=>api(`/admin/products/${product.id}`,{method:'PATCH',headers,body:JSON.stringify({[key]:e.target.checked})}).then(load)}/>{label}</label>)}</div><h4>Sync now</h4><div className="admin-sync-fields">{['inventory','cost','weight','supplier_status','images'].map(f=><label key={f}><input type="checkbox" checked={fields.includes(f)} onChange={()=>toggle(f)}/>{f.replace('_',' ')}</label>)}</div><button className="button button--dark" disabled={!fields.length} onClick={sync}>Sync selected fields</button><p>{state}</p><div className="admin-callout"><strong>Protected from ZQ overwrite</strong><p>Title, slug, descriptions, retail prices, categories, collections, tags, SEO, gallery order and customer-facing attributes remain controlled by Ivy &amp; Pearls.</p></div><h4>Recent sync history</h4>{(product.zq_sync_log||[]).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,10).map(r=><div className="admin-sync-log" key={r.id}><span>{date(r.created_at)}</span><span>{r.sync_type}</span><span>{(r.fields||[]).join(', ')}</span><span>{r.success?'Success':'Failed'}</span></div>)}</>}</div>}

function AdvancedTab({product,patch}){return <div className="admin-tab"><h3>Advanced</h3><div className="admin-form-grid"><SaveInput label="Menu order" type="number" value={product.menu_order||0} onSave={menu_order=>patch({menu_order})}/><Field label="Reviews"><select value={product.reviews_enabled?'yes':'no'} onChange={e=>patch({reviews_enabled:e.target.value==='yes'})}><option value="yes">Enabled</option><option value="no">Disabled</option></select></Field></div><SaveText label="Purchase note" value={product.purchase_note} rows={4} onSave={purchase_note=>patch({purchase_note})}/><Field label="Custom metadata (JSON)" hint="For structured internal metadata that does not belong in visible product copy."><textarea rows="10" defaultValue={JSON.stringify(product.custom_meta||{},null,2)} onBlur={e=>{try{patch({custom_meta:JSON.parse(e.target.value)})}catch{alert('Invalid JSON')}}}/></Field><div className="admin-readonly"><span>Product ID</span><b>{product.id}</b><span>Created</span><b>{date(product.created_at)}</b><span>Updated</span><b>{date(product.updated_at)}</b></div></div>}

function Catalogue({headers}){const [meta,setMeta]=useState(null),[type,setType]=useState('categories'),[name,setName]=useState(''),[state,setState]=useState('');const load=()=>api('/admin/catalogue-meta',{headers}).then(setMeta);useEffect(()=>{load()},[]);async function add(e){e.preventDefault();try{await api(`/admin/catalogue-meta/${type}`,{method:'POST',headers,body:JSON.stringify({name,slug:slugify(name),...(type==='attributes'?{type:'select'}:{})})});setName('');setState('Created.');load()}catch(e){setState(e.message)}}if(!meta)return <div className="loading-page">Loading catalogue…</div>;return <><div className="admin-title"><p className="eyebrow">Catalogue structure</p><h2>Taxonomies.</h2><p>Reusable categories, collections, tags and attributes keep product data consistent across the store.</p></div><div className="admin-taxonomy-tabs">{['categories','collections','tags','attributes'].map(t=><button className={type===t?'is-active':''} onClick={()=>setType(t)} key={t}>{t}</button>)}</div><div className="admin-panel"><form className="admin-inline-create" onSubmit={add}><input required placeholder={`New ${type.slice(0,-1)} name`} value={name} onChange={e=>setName(e.target.value)}/><button className="button button--dark">Add</button></form><p>{state}</p><div className="admin-taxonomy-list">{meta[type].map(r=><div key={r.id}><b>{r.name}</b><span>/{r.slug}/</span>{r.type&&<span>{r.type}</span>}</div>)}</div></div></>}

function ZqImport({headers}){const [q,setQ]=useState(''),[records,setRecords]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({title:'',slug:'',category:'earrings',collection:'',retailPricePounds:99,shortDescription:'',description:'',materialSummary:'',active:false}),[state,setState]=useState('');
 async function search(e){e?.preventDefault();setState('Searching ZQ…');try{const r=await api(`/admin/zq/products?q=${encodeURIComponent(q)}`,{headers});setRecords(r.records||r.list||[]);setState('')}catch(e){setState(e.message)}}
 async function choose(id){setState('Loading product…');try{const r=await api(`/admin/zq/products/${id}`,{headers});setSelected(r.product);setForm(f=>({...f,title:r.product.subject||'',slug:slugify(r.product.subject||''),description:r.product.description||''}));setState('')}catch(e){setState(e.message)}}
 async function submit(e){e.preventDefault();setState('Importing…');try{const r=await api(`/admin/zq/import/${selected.id}`,{method:'POST',headers,body:JSON.stringify({...form,retailPricePounds:Number(form.retailPricePounds)})});setState(`Imported ${r.slug} into Needs Review. Open Products to merchandise it before publishing.`);setSelected(null)}catch(e){setState(e.message)}}
 const f=n=>({value:form[n],onChange:e=>setForm(x=>({...x,[n]:e.target.type==='checkbox'?e.target.checked:e.target.value}))});
 return <><div className="admin-title"><p className="eyebrow">ZQ import inbox</p><h2>Supplier products.</h2><p>ZQ is the supplier layer, not your storefront CMS. Import products into review, then rewrite and organise them before publication.</p></div><form className="admin-search" onSubmit={search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Product name, ID or SKU"/><button className="button button--dark">Search ZQ</button></form><p>{state}</p><div className="zq-grid">{records.map(r=><button className="zq-card" onClick={()=>choose(r.id)} key={r.id}>{r.images?.[0]?.image&&<img src={r.images[0].image} alt=""/>}<span>{r.subject}</span><small>#{r.id}</small><em>Import as draft</em></button>)}</div>{selected&&<div className="admin-modal"><form onSubmit={submit}><button type="button" className="admin-modal__close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">ZQ → Ivy &amp; Pearls</p><h3>Prepare supplier product</h3><div className="form-grid"><label>Product title<input required {...f('title')}/></label><label>URL slug<input required pattern="[a-z0-9-]+" {...f('slug')}/></label><label>Primary category<select {...f('category')}><option value="rings">Rings</option><option value="necklaces">Necklaces</option><option value="earrings">Earrings</option><option value="bracelets">Bracelets</option></select></label><label>Starting retail price (£)<input type="number" min="1" step=".01" {...f('retailPricePounds')}/></label><label className="span-2">Short description<textarea {...f('shortDescription')}/></label><label className="span-2">Verified material summary<textarea {...f('materialSummary')} placeholder="Only enter verified material information."/></label></div><label className="check-line"><input type="checkbox" checked={form.active} onChange={f('active').onChange}/><span>Publish immediately (recommended off until review is complete)</span></label><button className="button button--dark">Import supplier product</button></form></div>}</>}

function Orders({headers}){const [orders,setOrders]=useState([]),[state,setState]=useState('');const load=()=>api('/admin/orders',{headers}).then(r=>setOrders(r.orders));useEffect(()=>{load()},[]);async function retry(id){setState('Submitting to ZQ…');try{await api(`/admin/orders/${id}/retry-zq`,{method:'POST',headers});setState('Submitted.');load()}catch(e){setState(e.message)}}return <><div className="admin-title"><p className="eyebrow">Orders</p><h2>Fulfilment.</h2><p>{state}</p></div><div className="admin-orders">{orders.map(o=><details key={o.id}><summary><b>{o.order_number}</b><span>{o.status.replaceAll('_',' ')}</span><span>{money(o.total_minor)}</span><span>{date(o.created_at)}</span></summary><div className="admin-order-body"><p>{o.email}</p><p>ZQ: {o.zq_platform_order_id||'Not yet submitted'} · {o.zq_status||'—'}</p><p>Tracking: {o.tracking_number||'Awaiting tracking'}</p>{o.order_items?.map(i=><p key={i.id}>{i.product_name} · {i.variant_name} × {i.quantity}</p>)}{o.status==='fulfilment_error'&&<button className="button button--dark" onClick={()=>retry(o.id)}>Retry ZQ fulfilment</button>}</div></details>)}</div></>}
