import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import CinematicHero from '../components/CinematicHero';
import ProductGrid from '../components/ProductGrid';
import Newsletter from '../components/Newsletter';
import Seo from '../components/Seo';
import {getProducts} from '../lib/api';
import {COLLECTIONS,SITE} from '../lib/config';
import {useBootstrap} from '../context/BootstrapContext';

export default function Home(){
 const boot=useBootstrap();const [products,setProducts]=useState(boot.homeProducts||[]);
 useEffect(()=>{if(!products.length&&!boot.configurationPending)getProducts({limit:16}).then(setProducts).catch(()=>{})},[]);
 const org={"@context":"https://schema.org","@type":"Organization",name:SITE.name,url:SITE.url,email:SITE.email,legalName:SITE.company};
 return <><Seo description="Discover quietly distinctive contemporary jewellery from Ivy & Pearls, chosen for everyday elegance." path="/" image="/images/hero-gsap.webp" jsonLd={org}/><CinematicHero/>
 <section className="section section--ivory"><div className="container"><div className="section-heading"><p className="eyebrow">Explore</p><h2>Featured <em>collections.</em></h2><p>Considered pieces for the details you return to every day.</p></div><div className="collection-grid">{COLLECTIONS.map((c,i)=><Link to={`/collections/${c.slug}/`} className="collection-card" key={c.slug}><div className="collection-card__media">{products[i]?.images?.[0]?<img src={products[i].images[0].url} alt={c.name} loading="lazy"/>:<div className="collection-card__fallback"><span>{c.name}</span></div>}</div><div><span>0{i+1}</span><h3>{c.name}</h3><p>{c.copy}</p><b>Discover ↗</b></div></Link>)}</div></div></section>
 <section className="section"><div className="container"><div className="section-heading section-heading--split"><div><p className="eyebrow">Just in</p><h2>New <em>arrivals.</em></h2></div><Link to="/new-arrivals/">View all ↗</Link></div><ProductGrid products={products.filter(p=>p.new_arrival).slice(0,4).length?products.filter(p=>p.new_arrival).slice(0,4):products.slice(0,4)}/></div></section>
 <section className="editorial-band"><div className="editorial-band__media"><img src="/images/editorial-jewellery.webp" alt="Ivy & Pearls jewellery styled in warm natural light" loading="lazy"/></div><div className="editorial-band__copy"><p className="eyebrow">Contemporary jewellery for daily rituals</p><h2>Light, <em>held close.</em></h2><p>Jewellery should feel considered without feeling precious. Pieces selected for ease, texture and the small rituals of getting dressed.</p><Link to="/the-ivy-edit/">Discover the Ivy Edit ↗</Link></div></section>
 <section className="section section--dark"><div className="container"><div className="section-heading section-heading--split section-heading--light"><div><p className="eyebrow">The Ivy Edit</p><h2>Chosen with <em>intention.</em></h2></div><p>A concise edit of pieces we return to for balance, wearability and quietly distinctive detail.</p></div><ProductGrid products={products.filter(p=>p.ivy_edit).slice(0,4).length?products.filter(p=>p.ivy_edit).slice(0,4):products.slice(4,8)}/></div></section>
 <section className="lifestyle"><div className="lifestyle__copy"><p className="eyebrow">Everyday, considered</p><h2>Made to move <em>with you.</em></h2><p>From first coffee to late dinners, jewellery that settles naturally into the way you dress.</p><Link to="/shop/">Shop all jewellery ↗</Link></div><div className="lifestyle__media"><img src="/images/lifestyle-jewellery.webp" alt="Ivy & Pearls jewellery worn as part of an everyday look" loading="lazy"/></div></section>
 <section className="section confidence"><div className="container"><div className="section-heading"><p className="eyebrow">Why Ivy & Pearls</p><h2>Chosen with <em>confidence.</em></h2></div><div className="confidence-grid"><article><span>01</span><h3>Product clarity</h3><p>Clear product information and considered imagery, so you can choose with confidence.</p></article><article><span>02</span><h3>Considered presentation</h3><p>A restrained, premium experience from discovery through to delivery.</p></article><article><span>03</span><h3>Client care</h3><p>Thoughtful support whenever you need a little guidance before or after ordering.</p></article></div></div></section>
 <section className="section section--ivory"><div className="container"><div className="section-heading"><p className="eyebrow">Styled by Ivy & Pearls</p><h2>Light, texture <em>and detail.</em></h2></div><div className="editorial-gallery">{['gallery-1.webp','gallery-2.webp','gallery-3.webp','gallery-4.webp','gallery-5.webp','gallery-6.webp'].map((f,i)=><figure key={f} className={`editorial-gallery__item editorial-gallery__item--${i+1}`}><img src={`/images/${f}`} alt="" loading="lazy"/></figure>)}</div></div></section>
 <Newsletter/></>;
}
